version: '2'
volumes:
 dbdata:

services:
 mysql:
  platform: linux/x86_64
  image: mysql:8
  container_name: mysql
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=pdm
  ports:
    - "3366:3306"